Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-06, with the labels that each got.

#90 FP-248: Blog FED
  src/lib/components/02-components/featured-resource/featured-resource--card.tsx
  src/lib/components/index.ts
  tailwind-theme-preset.js
Labels: 👍 Ready for Review

#91 FP-264: Cyber Education FE
  src/lib/components/02-components/callout/callout.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#94 Release - 06/04/2024
  src/lib/components/02-components/callout/callout.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#92 FP-436: Find a Partner and Find a Distributor Listing - FED
  src/lib/components/02-components/form/salesforce-search/salesforce-search.stories.tsx
  src/lib/components/02-components/form/salesforce-search/salesforce-search.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#99 Release - 06/06/2024
  src/lib/components/02-components/form/salesforce-search/salesforce-search.stories.tsx
  src/lib/components/02-components/form/salesforce-search/salesforce-search.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#96 feat(910): Play solid icon added
  src/lib/assets/img/icons/play-solid.svg
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#101 Release - 06/12/2024 - 1
  src/lib/assets/img/icons/play-solid.svg
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#95 FP-939: Hero Banner - Social Share
  README.md
  docs/api/socialShare.md
  src/lib/components/02-components/social-share/social-share.stories.tsx
  src/lib/components/02-components/social-share/social-share.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#102 Release - 06/12/2024 - 2
  README.md
  docs/api/socialShare.md
  src/lib/components/02-components/social-share/social-share.stories.tsx
  src/lib/components/02-components/social-share/social-share.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#98 FP-956: Create 404 and 500 pages
  src/lib/components/02-components/search-input/search-input-simple.tsx
  src/lib/components/index.ts
Labels: 👁 Review in progress

#104 Release - 06/17/2024 - 1
  src/lib/components/02-components/search-input/search-input-simple.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#97 FP-921: Product page components
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/featured-resource/featured-resource--card.tsx
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
  src/lib/components/02-components/slider/content-slider.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#105 Release - 06/18/2024
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/featured-resource/featured-resource--card.tsx
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
  src/lib/components/02-components/slider/content-slider.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#106 Release - 06/19/2024 - 1
  src/lib/components/02-components/marketo-reference/marketo-reference.stories.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#100 INTL Main Nav issues
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
Labels: 👍 Ready for Review

#108 Release - 06/26/2024
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
