Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-08, with the labels that each got.

#124 New release
  src/lib/components/02-components/cta-banner/cta-banner.tsx
Labels: 👍 Ready for Review

#126 New release
  src/lib/components/02-components/marketo-reference/marketo-reference.stories.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
Labels: 👍 Ready for Review

#127 FP-1109: Check announcement banner flyouts
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
Labels: 👍 Ready for Review

#128 FP-1109: Check announcement banner flyouts
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
Labels: 👍 Ready for Review

#129 New props for lists and CTA
  docs/api/cta.md
  src/lib/components/02-components/cta/cta.stories.tsx
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/list-item/list-item.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/list/list.stories.tsx
Labels: 👍 Ready for Review

#130 Sync develop
  docs/api/cta.md
  src/lib/components/02-components/cta/cta.stories.tsx
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/list-item/list-item.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/list/list.stories.tsx
Labels: 👍 Ready for Review

#131 Migration adjustments
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/table/table.tsx
Labels: 🎉 Passes Code Review, 🎉 Ready to Merge

#133 FP-1172: Fixes in form error messages styles
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#134 Release - 08/12/2024
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#136 NA: Landing Page Hero Component Is not Displaying Correctly.
  src/lib/components/02-components/cta-banner/cta-banner.tsx
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
Labels: 👍 Ready for Review

#138 Fix link problem in CTA
  src/lib/components/02-components/cta/cta.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#139 NA: Landing Page Hero Component Is not Displaying Correctly.
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#140 New release
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
Labels: 👍 Ready for Review

#141 feat(1172): Make form color white when the form has a bg color
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#142 Release - 08/14/2024
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
