Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-04, with the labels that each got.

#41 FP-785: Sign up form styles
  .storybook/manager.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/theme.ts
  README.md
  docs/api/hubspotFormWrapper.md
  package-lock.json
  package.json
  src/lib/assets/css/form.css
  src/lib/assets/img/icons/arrow-right-blue.svg
  src/lib/assets/img/icons/arrow-right-white.svg
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.stories.ts
  src/lib/components/02-components/form/hubspot-form-wrapper.stories.tsx
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#43 Release - 04/02/2024
  .storybook/manager.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  .storybook/theme.ts
  README.md
  docs/api/hubspotFormWrapper.md
  package-lock.json
  package.json
  src/lib/assets/css/form.css
  src/lib/assets/img/icons/arrow-right-blue.svg
  src/lib/assets/img/icons/arrow-right-white.svg
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.stories.ts
  src/lib/components/02-components/form/hubspot-form-wrapper.stories.tsx
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#45 FP-809: Support for user defined classes in footer menu
  src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
Labels: 👁 Review in progress

#44 FP-320: Table + Table Row + Table Column
  src/lib/assets/css/main-menu.css
  src/lib/components/00-tokens/color/color-shared.tsx
  src/lib/components/02-components/table/data-table-provider.tsx
  src/lib/components/02-components/table/table-column.tsx
  src/lib/components/02-components/table/table-pager.tsx
  src/lib/components/02-components/table/table-row.tsx
  src/lib/components/02-components/table/table-wrapper.tsx
  src/lib/components/02-components/table/table.stories.tsx
  src/lib/components/02-components/table/table.tsx
  src/lib/components/index.ts
  src/lib/hooks/use-media-query.ts
Labels: 👁 Review in progress

#47 Release - 04/16/2024
  src/lib/assets/css/main-menu.css
  src/lib/components/00-tokens/color/color-shared.tsx
  src/lib/components/02-components/table/data-table-provider.tsx
  src/lib/components/02-components/table/table-column.tsx
  src/lib/components/02-components/table/table-pager.tsx
  src/lib/components/02-components/table/table-row.tsx
  src/lib/components/02-components/table/table-wrapper.tsx
  src/lib/components/02-components/table/table.stories.tsx
  src/lib/components/02-components/table/table.tsx
  src/lib/components/index.ts
  src/lib/hooks/use-media-query.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#38 FP-301: Image and Content Slide and Slider - FED
  .storybook/preview.ts
  README.md
  docs/api/content-slider.md
  src/lib/assets/css/animation.css
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/chevron-down.svg
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/02-components/slider/content-slider.stories.tsx
  src/lib/components/02-components/slider/content-slider.tsx
  src/lib/components/index.ts
Labels: 👁 Review in progress

#49 Release - 04/18/2024
  .storybook/preview.ts
  README.md
  docs/api/content-slider.md
  src/lib/assets/css/animation.css
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/chevron-down.svg
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/02-components/slider/content-slider.stories.tsx
  src/lib/components/02-components/slider/content-slider.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#50 feat: support anchor tags
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#51 Release - 04/23/2024
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#48 FP-823: Header Changes
  src/lib/assets/css/form.css
  src/lib/assets/css/main-menu.css
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/search-input/search-input.tsx
Labels: 👉 Needs Work, ❔ Question

#54 Release - 04/24/2024
  src/lib/assets/css/form.css
  src/lib/assets/css/main-menu.css
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/search-input/search-input.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#57 Match navigation style with prod
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#58 Release - 04/29/2024 - 1
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
Labels: 🎉 Passes Code Review, 🎉 Ready to Merge

#61 Navbar fixes
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#62 Release - 04/30/2024 - 1
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#52 FP-792: Footer Navigation Update
  src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
Labels: 👍 Ready for Review

#63 Release 04/30/2024 - 2
  src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
