Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-09, with the labels that each got.

#143 Add missing style on forms
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#144 Release September 4th 2024
  src/lib/assets/css/form.css
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#145 Add on click event to resource list item
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
Labels: 🎉 Passes Code Review

#146 New release September 13rd 2024
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#147 Re-Deploy Shiny sticky button (site wide) in D10
  src/lib/assets/css/form.css
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Ready to Merge

#148 New release September 23rd 2024
  src/lib/assets/css/form.css
  src/lib/assets/css/main-menu.css
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
