Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-07, with the labels that each got.

#109 FP-NOTICKET: header & footer layout
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/sticky-header/sticky-header.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#110 Update develop
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/sticky-header/sticky-header.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#111 Release - 07/04/2024
  src/lib/components/02-components/cta/cta.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#112 Release - 07/09/2024
  src/lib/components/02-components/list/list.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#114 Release - 07/11/2024
  src/lib/components/02-components/callout/callout.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#113 FP-1043, FP-1042: Slider fixes
  src/lib/components/02-components/slider/content-slider.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#115 FP-737: Readme updated
  README.md
Labels: 👍 Ready for Review

#116 Release - 07/17/2024 - 1
  README.md
  src/lib/components/02-components/slider/content-slider.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#118 FP-1080: Logogrid not showing sub title field
  docs/api/logoGrid.md
  src/lib/components/02-components/logo-grid/logo-grid.stories.tsx
  src/lib/components/02-components/logo-grid/logo-grid.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#117 FP-1082: landing page final plea cta width and image bleed
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
Labels: 🎉 Passes Code Review, 👁 Review in progress

#119 FP-1080: Logogrid not showing sub title field
  docs/api/logoGrid.md
  src/lib/components/02-components/logo-grid/logo-grid.stories.tsx
  src/lib/components/02-components/logo-grid/logo-grid.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#120 FP-1097: Podcast minor styling changes
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
  src/lib/components/02-components/podcast/podcast.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#121 FP-1097: Podcast minor styling changes
  src/lib/components/02-components/podcast/podcast.tsx
Labels: 🎉 Ready to Merge

#122 Create new version for the cta banner
  docs/api/ctaBanner.md
  src/lib/components/02-components/cta-banner/cta-banner.stories.tsx
  src/lib/components/02-components/cta-banner/cta-banner.tsx
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
Labels: 👍 Ready for Review
