Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-05, with the labels that each got.

#53 FP-294: Featured resource.
  README.md
  docs/api/callout.md
  docs/api/featuredResourceCard.md
  docs/api/featuredResourceListItem.md
  src/lib/assets/img/icons/download.svg
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/featured-resource/featured-resource--card.tsx
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#65 Release 05/02/2024 - 1
  README.md
  docs/api/callout.md
  docs/api/featuredResourceCard.md
  docs/api/featuredResourceListItem.md
  src/lib/assets/img/icons/download.svg
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/featured-resource/featured-resource--card.tsx
  src/lib/components/02-components/featured-resource/featured-resource--list-item.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#56 FP-461: Breadcrumb React Component - FED
  .storybook/main.ts
  README.md
  docs/api/breadcrumb.md
  package-lock.json
  package.json
  src/lib/assets/img/icons/chevron-left.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/01-elements/link/link.stories.tsx
  src/lib/components/02-components/breadcrumb/breadcrumb.stories.ts
  src/lib/components/02-components/breadcrumb/breadcrumb.tsx
  src/lib/components/02-components/slider/content-slider.stories.tsx
  src/lib/components/index.ts
Labels: 👉 Needs Work

#59 FP-304: List + List Item components
  src/lib/assets/img/icons/circle-checkmark.svg
  src/lib/components/02-components/list-item/list-item.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/list/list.stories.tsx
  src/lib/components/02-components/list/list.tsx
  src/lib/components/index.ts
Labels: 👁 Review in progress

#66 Release - 05/02/2024 - 2
  .storybook/main.ts
  README.md
  docs/api/breadcrumb.md
  package-lock.json
  package.json
  src/lib/assets/img/icons/chevron-left.svg
  src/lib/assets/img/icons/circle-checkmark.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/01-elements/link/link.stories.tsx
  src/lib/components/02-components/breadcrumb/breadcrumb.stories.ts
  src/lib/components/02-components/breadcrumb/breadcrumb.tsx
  src/lib/components/02-components/list-item/list-item.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/list/list.stories.tsx
  src/lib/components/02-components/list/list.tsx
  src/lib/components/02-components/slider/content-slider.stories.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#60 FP-307: External Form Reference FE
  docs/api/marketoReference.md
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.stories.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
  src/lib/components/index.ts
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#67 Release - 05/02/2024 - 3
  docs/api/marketoReference.md
  src/lib/components/02-components/form/hubspot-form-wrapper.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.stories.tsx
  src/lib/components/02-components/marketo-reference/marketo-reference.tsx
  src/lib/components/index.ts
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#55 FP-278: Announcement banners - Masthead and Flyout
  src/lib/assets/img/icons/close-filled.svg
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.stories.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.stories.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#68 Release - 05/06/2024 - 1
  src/lib/assets/img/icons/close-filled.svg
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.stories.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.stories.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#71 FP-304: Fixes for list item icon variant
  src/lib/components/02-components/list-item/list-item.tsx
Labels: 👁 Review in progress

#73 Release - 05/09/2024 - 1
  src/lib/components/02-components/list-item/list-item.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#70 feat(834): Excluded lancode support added for language switcher
  docs/api/languageSwitcher.md
  src/lib/components/02-components/menus/language-switcher/language-switcher.stories.tsx
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
Labels: 👁 Review in progress

#74 Release - 05/09/2024 - 2
  docs/api/languageSwitcher.md
  src/lib/components/02-components/menus/language-switcher/language-switcher.stories.tsx
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#75 feat(260): Social media icons exported
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#76 Branch update
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#77 FP-316: refactor icon logic and add extra icons
  .gitignore
  package.json
  scripts/create-icons-story.mjs
  scripts/create-icons.mjs
  src/lib/assets/img/icons/ai.svg
  src/lib/assets/img/icons/award.svg
  src/lib/assets/img/icons/bio.svg
  src/lib/assets/img/icons/blog.svg
  src/lib/assets/img/icons/clipboard.svg
  src/lib/assets/img/icons/cloud-server.svg
  src/lib/assets/img/icons/cloud-shield.svg
  src/lib/assets/img/icons/customer.svg
  src/lib/assets/img/icons/cyber-education.svg
  src/lib/assets/img/icons/datasheet.svg
  src/lib/assets/img/icons/document.svg
  src/lib/assets/img/icons/document2.svg
  src/lib/assets/img/icons/firewall.svg
  src/lib/assets/img/icons/gear-noded.svg
  src/lib/assets/img/icons/global-connections.svg
  src/lib/assets/img/icons/myth.svg
  src/lib/assets/img/icons/planning.svg
  src/lib/assets/img/icons/podcast.svg
  src/lib/assets/img/icons/scalable.svg
  src/lib/assets/img/icons/shield.svg
  src/lib/assets/img/icons/solution-brief.svg
  src/lib/assets/img/icons/threat-protection.svg
  src/lib/assets/img/icons/webcast.svg
  src/lib/components/00-tokens/icons/.gitkeep
  src/lib/components/00-tokens/icons/icons.stories.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.tsx
  src/lib/components/02-components/breadcrumb/breadcrumb.tsx
  src/lib/components/02-components/callout/callout.tsx
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-links/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/menus/menu-links/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/search-input/search-input.tsx
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/02-components/table/table.stories.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#78 Release - 05/15/2024
  .gitignore
  package.json
  scripts/create-icons-story.mjs
  scripts/create-icons.mjs
  src/lib/assets/img/icons/ai.svg
  src/lib/assets/img/icons/award.svg
  src/lib/assets/img/icons/bio.svg
  src/lib/assets/img/icons/blog.svg
  src/lib/assets/img/icons/clipboard.svg
  src/lib/assets/img/icons/cloud-server.svg
  src/lib/assets/img/icons/cloud-shield.svg
  src/lib/assets/img/icons/customer.svg
  src/lib/assets/img/icons/cyber-education.svg
  src/lib/assets/img/icons/datasheet.svg
  src/lib/assets/img/icons/document.svg
  src/lib/assets/img/icons/document2.svg
  src/lib/assets/img/icons/firewall.svg
  src/lib/assets/img/icons/gear-noded.svg
  src/lib/assets/img/icons/global-connections.svg
  src/lib/assets/img/icons/myth.svg
  src/lib/assets/img/icons/planning.svg
  src/lib/assets/img/icons/podcast.svg
  src/lib/assets/img/icons/scalable.svg
  src/lib/assets/img/icons/shield.svg
  src/lib/assets/img/icons/solution-brief.svg
  src/lib/assets/img/icons/threat-protection.svg
  src/lib/assets/img/icons/webcast.svg
  src/lib/components/00-tokens/icons/.gitkeep
  src/lib/components/00-tokens/icons/icons.stories.tsx
  src/lib/components/02-components/banners/flyout/flyout-banner.tsx
  src/lib/components/02-components/banners/masthead/masthead-banner.tsx
  src/lib/components/02-components/breadcrumb/breadcrumb.tsx
  src/lib/components/02-components/callout/callout.tsx
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/cta/cta.tsx
  src/lib/components/02-components/featured-resource/ featured-resource.stories.tsx
  src/lib/components/02-components/list-item/list-item.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-links/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/menus/menu-links/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/search-input/search-input.tsx
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/02-components/table/table.stories.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#72 FP-434: Search FE
  .prettierrc
  src/lib/assets/img/icons/chevron-down.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/02-components/form/site-search/site-search.stories.tsx
  src/lib/components/02-components/form/site-search/site-search.tsx
  src/lib/components/02-components/pager/pager.stories.tsx
  src/lib/components/02-components/pager/pager.tsx
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#79 FP-434: Search Follow up
  src/lib/components/02-components/form/site-search/site-search.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#80 Release - 05/16/2024
  .prettierrc
  src/lib/assets/img/icons/chevron-down.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/02-components/form/site-search/site-search.stories.tsx
  src/lib/components/02-components/form/site-search/site-search.tsx
  src/lib/components/02-components/pager/pager.stories.tsx
  src/lib/components/02-components/pager/pager.tsx
  src/lib/components/02-components/slider/content-slide-item.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#81 feat(908): Add link attributes to pager links
  src/lib/components/02-components/pager/pager.tsx
Labels: 👁 Review in progress

#83 Release - 05/20/2024
  src/lib/components/02-components/breadcrumb/breadcrumb.tsx
  src/lib/components/02-components/pager/pager.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#84 FP-928: Wire up the Image component
  docs/api/img.md
  src/lib/components/01-elements/img/img.stories.tsx
  src/lib/components/01-elements/img/img.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#85 Release - 05/21/2024
  docs/api/img.md
  src/lib/components/01-elements/img/img.stories.tsx
  src/lib/components/01-elements/img/img.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#86 FP-248: Social share component created
  src/lib/components/02-components/social-share/social-share.stories.tsx
  src/lib/components/02-components/social-share/social-share.tsx
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#88 Release - 05/27/2024 -1
  docs/api/ctaBanner.md
  src/lib/components/02-components/cta-banner/cta-banner.stories.tsx
  src/lib/components/02-components/cta-banner/cta-banner.tsx
  src/lib/components/02-components/social-share/social-share.stories.tsx
  src/lib/components/02-components/social-share/social-share.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
