Repository youonlylivetwice/forcepoint-shared-components, pull requests merged in 2024-02, with the labels that each got.

#8 Language switcher
  README.md
  docs/languageSwitcher.md
  src/lib/components/02-components/menus/language-switcher/language-switcher.stories.tsx
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/index.ts
Labels: 👁 Review in progress

#3 FP-242: Search input
  docs/searchInput.md
  src/lib/assets/img/icons/close-thick.svg
  src/lib/assets/img/icons/search-thick.svg
  src/lib/assets/img/icons/search.svg
  src/lib/components/02-components/search-input/search-input.stories.tsx
  src/lib/components/02-components/search-input/search-input.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#10 chore: update GH actions
  .github/workflows/deploy.yaml
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#11 FP-666: Update docs
  README.md
  docs/ATOMIC_DESIGN.md
  docs/CONTRIBUTING.md
  docs/api/branding.md
  docs/api/button.md
  docs/api/languageSwitcher.md
  docs/api/link.md
  docs/api/searchInput.md
  docs/api/secondaryMenu.md
  docs/api/typography.md
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#13 FP-339: Social menu
  README.md
  docs/api/socialMenu.md
  src/lib/assets/img/icons/facebook.svg
  src/lib/assets/img/icons/linkedin.svg
  src/lib/assets/img/icons/rss.svg
  src/lib/assets/img/icons/twitter.svg
  src/lib/assets/img/icons/youtube.svg
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/menus/social-menu/social-menu.stories.tsx
  src/lib/components/02-components/menus/social-menu/social-menu.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#12 FP-340: Footer menu
  README.md
  docs/api/footerMenu.md
  src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#16 Release - 02/13/2024
  README.md
  docs/ATOMIC_DESIGN.md
  docs/CONTRIBUTING.md
  docs/api/branding.md
  docs/api/button.md
  docs/api/footerMenu.md
  docs/api/languageSwitcher.md
  docs/api/link.md
  docs/api/searchInput.md
  docs/api/secondaryMenu.md
  docs/api/socialMenu.md
  docs/api/typography.md
  src/lib/assets/img/icons/facebook.svg
  src/lib/assets/img/icons/linkedin.svg
  src/lib/assets/img/icons/rss.svg
  src/lib/assets/img/icons/twitter.svg
  src/lib/assets/img/icons/youtube.svg
  src/lib/components/02-components/menus/footer/footer-menu.stories.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/menus/social-menu/social-menu.stories.tsx
  src/lib/components/02-components/menus/social-menu/social-menu.tsx
  src/lib/components/index.ts
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#14 FP-349: Main menu - frontend.
  README.md
  docs/api/card380.md
  docs/api/mainMenu.md
  docs/api/navHighlight.md
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/chevron-right.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/01-elements/button/button.tsx
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/branding/branding.stories.tsx
  src/lib/components/02-components/cards/card-380/card-380.stories.ts
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.stories.ts
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.stories.ts
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.stories.ts
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Functional Review, 🎉 Ready to Merge

#19 Release - 02/15/2024
  README.md
  docs/api/card380.md
  docs/api/mainMenu.md
  docs/api/navHighlight.md
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/chevron-right.svg
  src/lib/components/01-elements/button/button.stories.tsx
  src/lib/components/01-elements/button/button.tsx
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/branding/branding.stories.tsx
  src/lib/components/02-components/cards/card-380/card-380.stories.ts
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.stories.ts
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.stories.ts
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.stories.ts
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#20 Fp 244 footer and header adjustments
  docs/api/branding.md
  docs/api/secondaryMenu.md
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/twitter.svg
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/branding/branding.tsx
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.stories.ts
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.stories.ts
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/search-input/search-input.stories.tsx
  src/lib/components/02-components/search-input/search-input.tsx
  src/lib/components/index.ts
  src/lib/index.ts
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#21 Release - 27/02/2024
  docs/api/branding.md
  docs/api/secondaryMenu.md
  src/lib/assets/css/theme.css
  src/lib/assets/img/icons/twitter.svg
  src/lib/components/01-elements/link/link.tsx
  src/lib/components/02-components/branding/branding.tsx
  src/lib/components/02-components/cards/card-380/card-380.tsx
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.stories.ts
  src/lib/components/02-components/cards/nav-highlight/nav-highlight.tsx
  src/lib/components/02-components/ctas/main-nav-link/main-nav-link.tsx
  src/lib/components/02-components/ctas/nav-link/nav-link.stories.ts
  src/lib/components/02-components/ctas/nav-link/nav-link.tsx
  src/lib/components/02-components/menus/footer/footer-menu.tsx
  src/lib/components/02-components/menus/language-switcher/language-switcher.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.stories.tsx
  src/lib/components/02-components/menus/main-menu/main-menu.tsx
  src/lib/components/02-components/menus/menu-modal/menu-modal.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.stories.tsx
  src/lib/components/02-components/menus/secondary-menu/secondary-menu.tsx
  src/lib/components/02-components/menus/social-menu/social-menu-icon.tsx
  src/lib/components/02-components/search-input/search-input.stories.tsx
  src/lib/components/02-components/search-input/search-input.tsx
  src/lib/components/index.ts
  src/lib/index.ts
  tailwind-theme-preset.js
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge
